import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/layouts/Header'
import Footer from '@/components/layouts/Footer'
import RecoilProvider from '@/recoil/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilProvider>
          <Header />
            {children}
          <Footer />
        </RecoilProvider>
      </body>
    </html>
  )
}
